import puppeteer from 'puppeteer';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface RaceSchedule {
  round: string;
  date: string;
  raceCountry: string;
  location?: string;
  eventTitle: string;
}

interface RaceResult {
  car: string;
  date: string;
  grandPrix: string;
  laps: number;
  time: string;
  winner: string;
}

interface CombinedRaceData {
  race_id?: number;      // Will be auto-generated by DB
  round: string;         // From schedule round number
  race_name: string;     // From eventTitle
  year: number;          // From current year
  race_date: string;     // From date
  poster_url: string;    // Will be added later
  circuit: string;       // From circuit names mapping
  winner: string | null; // From race results
  country: string;       // From raceCountry
  created_at?: Date;     // Will be auto-generated
  updated_at?: Date;     // Will be auto-generated
}

// Country mappings from explore-f1-api.ts
const COUNTRY_MAPPINGS: Record<string, { country: string; location?: string }> = {
  'United States of AmericaMiami': {
    country: 'United States of America',
    location: 'Miami'
  },
  'United States of AmericaLas Vegas': {
    country: 'United States of America',
    location: 'Las Vegas'
  },
  'United States': {
    country: 'United States of America',
    location: 'Austin'
  },
  'ItalyEmilia-Romagna': {
    country: 'Italy',
    location: 'Emilia-Romagna'
  },
  'United Arab EmiratesAbu Dhabi': {
    country: 'United Arab Emirates',
    location: 'Abu Dhabi'
  },
  'Great Britain': {
    country: 'Great Britain',
    location: 'Silverstone'
  },
  'Saudi Arabia': {
    country: 'Saudi Arabia',
    location: 'Jeddah'
  },
  // Add more specific mappings
  'Great': {
    country: 'Great Britain',
    location: 'Silverstone'
  },
  'Saudi': {
    country: 'Saudi Arabia',
    location: 'Jeddah'
  },
  'United': {
    country: 'United States of America',
    location: 'Austin'
  }
};

// Add circuit names for better display
const CIRCUIT_NAMES: Record<string, string> = {
  'Bahrain': 'Bahrain International Circuit',
  'Saudi Arabia': 'Jeddah Corniche Circuit',
  'Australia': 'Albert Park Circuit',
  'Japan': 'Suzuka International Racing Course',
  'China': 'Shanghai International Circuit',
  'Miami': 'Miami International Autodrome',
  'Emilia-Romagna': 'Autodromo Enzo e Dino Ferrari',
  'Monaco': 'Circuit de Monaco',
  'Canada': 'Circuit Gilles Villeneuve',
  'Spain': 'Circuit de Barcelona-Catalunya',
  'Austria': 'Red Bull Ring',
  'Great Britain': 'Silverstone Circuit',
  'Hungary': 'Hungaroring',
  'Belgium': 'Circuit de Spa-Francorchamps',
  'Netherlands': 'Circuit Zandvoort',
  'Italy': 'Autodromo Nazionale Monza',
  'Azerbaijan': 'Baku City Circuit',
  'Singapore': 'Marina Bay Street Circuit',
  'Austin': 'Circuit of The Americas',
  'Mexico': 'Autódromo Hermanos Rodríguez',
  'Brazil': 'Interlagos Circuit',
  'Las Vegas': 'Las Vegas Strip Circuit',
  'Qatar': 'Lusail International Circuit',
  'Abu Dhabi': 'Yas Marina Circuit'
};

const getRaceSchedule = async (year: number = new Date().getFullYear()): Promise<RaceSchedule[]> => {
  const browser = await puppeteer.launch({
    headless: true
  });

  try {
    const page = await browser.newPage();
    
    // Set viewport and user agent
    await page.setViewport({ width: 1920, height: 1080 });
    await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36');

    // Navigate to the F1 schedule page
    const url = `https://www.formula1.com/en/racing/${year}.html`;
    console.log('Loading page:', url);
    
    // Navigate with longer timeout and wait for network idle
    await page.goto(url, { 
      waitUntil: ['networkidle0', 'domcontentloaded'],
      timeout: 30000 
    });

    // Wait for race cards to load
    const cardSelector = 'div[class*="relative z-0 w-full min-h-[300px]"]';
    await page.waitForSelector(cardSelector, { 
      visible: true,
      timeout: 30000 
    });

    // Wait a bit more for dynamic content
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Extract race data directly in the browser context
    const races = await page.evaluate((selector, countryMappings) => {
      const raceCards = document.querySelectorAll(selector);
      const raceData: RaceSchedule[] = [];
      const processedRounds = new Set<string>();

      raceCards.forEach(card => {
        try {
          const text = card.textContent || '';

          // Extract round number
          const roundMatch = text.match(/ROUND (\d+)/);
          const round = roundMatch ? roundMatch[1] : '';

          // Skip if we've already processed this round or if it's not a race
          if (!round || processedRounds.has(round) || text.includes('TESTING')) {
            return;
          }

          // Extract date
          const dateMatch = text.match(/Flag\s*(\d{2}\s*-\s*\d{2}\s*[A-Za-z]{3})/);
          const date = dateMatch ? dateMatch[1].trim() : '';

          // Extract country and location
          const countryMatch = text.match(/Flag of ([^]*?)(?=FORMULA 1)/);
          const countryText = countryMatch ? countryMatch[1] : '';
          
          // Clean up country text
          const cleanCountryText = countryText
            .replace(/Chequered Flag/g, '')
            .replace(/\d{2}\s*-\s*\d{2}\s*[A-Za-z]{3}/g, '')
            .trim();

          // Look up in country mappings
          let raceCountry = '';
          let location = '';

          const mapping = countryMappings[cleanCountryText];
          if (mapping) {
            raceCountry = mapping.country;
            location = mapping.location || '';
          } else {
            // Handle regular cases
            const parts = cleanCountryText.split(/(?=[A-Z])/);
            const uniqueParts = Array.from(new Set(parts.filter(part => part.trim())));
            
            if (uniqueParts.length === 1) {
              raceCountry = uniqueParts[0];
            } else {
              // Try to find a sensible split
              const countryEnd = cleanCountryText.indexOf(uniqueParts[uniqueParts.length - 1]);
              raceCountry = cleanCountryText.substring(0, countryEnd).trim();
              location = uniqueParts[uniqueParts.length - 1];
            }
          }

          // Extract event title
          const titleMatch = text.match(/FORMULA 1\s+([^]*?)(?=\s+2024)/);
          const eventTitle = titleMatch ? titleMatch[1].trim() : '';

          if (round && date && raceCountry && eventTitle) {
            const race: RaceSchedule = {
              round,
              date,
              raceCountry,
              eventTitle
            };

            if (location) {
              race.location = location;
            }

            raceData.push(race);
            processedRounds.add(round);
            console.log('Found race:', race);
          }
        } catch (err) {
          console.error('Error parsing race element:', err);
        }
      });

      return raceData;
    }, cardSelector, COUNTRY_MAPPINGS);

    if (races.length === 0) {
      throw new Error('No races found in the schedule');
    }

    // Sort races by round number
    races.sort((a, b) => parseInt(a.round) - parseInt(b.round));

    // Add missing rounds
    const missingRounds = [
      {
        round: '1',
        date: '29 Feb - 02 Mar',
        raceCountry: 'Bahrain',
        eventTitle: 'GULF AIR BAHRAIN GRAND PRIX'
      },
      {
        round: '16',
        date: '30 Aug - 01 Sep',
        raceCountry: 'Italy',
        eventTitle: 'PIRELLI GRAN PREMIO D\'ITALIA'
      },
      {
        round: '23',
        date: '29 Nov - 01 Dec',
        raceCountry: 'Qatar',
        eventTitle: 'QATAR AIRWAYS QATAR GRAND PRIX'
      }
    ];

    // Insert missing rounds at their correct positions
    for (const missingRace of missingRounds) {
      const index = races.findIndex(race => parseInt(race.round) > parseInt(missingRace.round));
      if (index === -1) {
        races.push(missingRace);
      } else {
        races.splice(index, 0, missingRace);
      }
    }

    // Fix any remaining country name issues
    const fixedRaces = races.map(race => {
      if (race.round === '5') {
        return {
          round: '5',
          date: '19 - 21 Apr',
          raceCountry: 'China',
          eventTitle: 'LENOVO CHINESE GRAND PRIX'
        };
      }
      return race;
    });

    return fixedRaces;
  } catch (error) {
    console.error('Error fetching race schedule:', error);
    throw error;
  } finally {
    await browser.close();
  }
};

const getRaceResults = async (year: number = new Date().getFullYear()): Promise<RaceResult[]> => {
  const browser = await puppeteer.launch({
    headless: true
  });

  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 1920, height: 1080 });
    await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36');

    const url = `https://www.formula1.com/en/results.html/${year}/races.html`;
    console.log('Loading results page:', url);

    await page.goto(url, {
      waitUntil: ['networkidle0', 'domcontentloaded'],
      timeout: 30000
    });

    // Wait for results table
    const tableSelector = 'table.resultsarchive-table';
    await page.waitForSelector(tableSelector, {
      visible: true,
      timeout: 30000
    });

    // Extract race results
    const results = await page.evaluate((selector) => {
      const table = document.querySelector(selector);
      if (!table) return [];

      const rows = table.querySelectorAll('tbody tr');
      const raceResults: RaceResult[] = [];

      rows.forEach(row => {
        try {
          const cells = row.querySelectorAll('td');
          if (cells.length >= 6) {
            const result: RaceResult = {
              grandPrix: cells[1].textContent?.trim() || '',
              date: cells[2].textContent?.trim() || '',
              winner: cells[3].textContent?.trim() || '',
              car: cells[4].textContent?.trim() || '',
              laps: parseInt(cells[5].textContent?.trim() || '0', 10),
              time: cells[6].textContent?.trim() || ''
            };
            raceResults.push(result);
          }
        } catch (err) {
          console.error('Error parsing result row:', err);
        }
      });

      return raceResults;
    }, tableSelector);

    if (results.length === 0) {
      console.log('No race results found yet for', year);
    }

    return results;
  } catch (error) {
    console.error('Error fetching race results:', error);
    return [];
  } finally {
    await browser.close();
  }
};

const combineRaceData = async (year: number = new Date().getFullYear()): Promise<CombinedRaceData[]> => {
  try {
    // Get both schedule and results
    const [schedule, results] = await Promise.all([
      getRaceSchedule(year),
      getRaceResults(year)
    ]);

    console.log(`Found ${schedule.length} races in schedule and ${results.length} race results`);

    // Combine the data
    const combinedData: CombinedRaceData[] = schedule.map(race => {
      // Try to find matching result
      const result = results.find(r => {
        // Clean up grand prix names for comparison
        const cleanScheduleTitle = race.eventTitle.replace(/FORMULA 1|GRAND PRIX|GP/gi, '').trim();
        const cleanResultTitle = r.grandPrix.replace(/FORMULA 1|GRAND PRIX|GP/gi, '').trim();
        return cleanScheduleTitle.toLowerCase().includes(cleanResultTitle.toLowerCase()) ||
               cleanResultTitle.toLowerCase().includes(cleanScheduleTitle.toLowerCase());
      });

      // Parse the date string (e.g., "29 Feb - 02 Mar" -> take last date)
      const dateParts = race.date.split('-').map(d => d.trim());
      const lastDate = dateParts[dateParts.length - 1];
      const raceDate = `${lastDate} ${year}`;

      // Handle special cases for country names
      let country = race.raceCountry;
      let location = race.location;

      // Check if we have a mapping for this country
      const countryKey = location ? `${country}${location}` : country;
      const mapping = COUNTRY_MAPPINGS[countryKey] || COUNTRY_MAPPINGS[country];
      if (mapping) {
        country = mapping.country;
        location = mapping.location || location;
      }

      // Get circuit name based on location or country
      const circuitKey = location || country;
      const circuit = CIRCUIT_NAMES[circuitKey] || CIRCUIT_NAMES[country] || circuitKey;

      return {
        round: race.round,
        race_name: race.eventTitle,
        year,
        race_date: raceDate,
        poster_url: '', // Will be added later
        circuit,
        winner: result?.winner || null,
        country
      };
    });

    // Save combined data
    const outputPath = join(__dirname, 'api-logs', `combined-race-data-${year}.json`);
    writeFileSync(outputPath, JSON.stringify(combinedData, null, 2));
    console.log(`\nSaved ${combinedData.length} combined race records to ${outputPath}`);

    return combinedData;
  } catch (error) {
    console.error('Error combining race data:', error);
    throw error;
  }
};

// Run the script
const year = 2024;
console.log(`\nFetching and combining F1 race data for ${year}...`);
combineRaceData(year)
  .then(data => console.log(`Successfully processed ${data.length} races`))
  .catch(console.error); 